package com.zhaoguhong.mybatis.encrypt.test.dao;

import com.zhaoguhong.mybatis.encrypt.test.entity.User;
import org.apache.ibatis.jdbc.SQL;


public class UserSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jun 12 15:27:08 CST 2021
     */
    public String insertSelective(User record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("user");

        if (record.getId() != null) {
            sql.VALUES("`id`", "#{id,jdbcType=BIGINT}");
        }

        if (record.getPassword() != null) {
            sql.VALUES("`password`", "#{password,jdbcType=VARCHAR}");
        }

        if (record.getUserName() != null) {
            sql.VALUES("`user_name`", "#{userName,jdbcType=VARCHAR}");
        }

        if (record.getAge() != null) {
            sql.VALUES("`age`", "#{age,jdbcType=INTEGER}");
        }

        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Jun 12 15:27:08 CST 2021
     */
    public String updateByPrimaryKeySelective(User record) {
        SQL sql = new SQL();
        sql.UPDATE("user");

        if (record.getPassword() != null) {
            sql.SET("`password` = #{password,jdbcType=VARCHAR}");
        }

        if (record.getUserName() != null) {
            sql.SET("`user_name` = #{userName,jdbcType=VARCHAR}");
        }

        if (record.getAge() != null) {
            sql.SET("`age` = #{age,jdbcType=INTEGER}");
        }

        sql.WHERE("`id` = #{id,jdbcType=BIGINT}");

        return sql.toString();
    }
}
