package com.zhaoguhong.mybatis.encrypt.test.dao;

import com.zhaoguhong.mybatis.encrypt.test.entity.User;
import java.util.Map;
import org.apache.ibatis.annotations.Mapper;

/**
 * @author guhong
 * @date 2021/6/13
 */

@Mapper
public interface UserWithXmlMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table user
   *
   * @mbg.generated Sun Jun 13 23:06:34 CST 2021
   */
  int deleteByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table user
   *
   * @mbg.generated Sun Jun 13 23:06:34 CST 2021
   */
  int insert(User record);

  int insertWithMap(Map<String,Object> record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table user
   *
   * @mbg.generated Sun Jun 13 23:06:34 CST 2021
   */
  int insertSelective(User record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table user
   *
   * @mbg.generated Sun Jun 13 23:06:34 CST 2021
   */
  User selectByPrimaryKey(Long id);

  Map<String, Object> selectByPrimaryKeyWithReturnMap(Long id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table user
   *
   * @mbg.generated Sun Jun 13 23:06:34 CST 2021
   */
  int updateByPrimaryKeySelective(User record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table user
   *
   * @mbg.generated Sun Jun 13 23:06:34 CST 2021
   */
  int updateByPrimaryKey(User record);
}
