package com.zhaoguhong.mybatis.encrypt.test.entity;

import com.zhaoguhong.mybatis.encrypt.annotation.CryptField;
import java.io.Serializable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class User implements Serializable {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * user.id
   *
   * @mbg.generated Sat Jun 12 13:37:40 CST 2021
   */
  private Long id;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * user.password
   *
   * @mbg.generated Sat Jun 12 13:37:40 CST 2021
   */
  private String password;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * user.user_name
   *
   * @mbg.generated Sat Jun 12 13:37:40 CST 2021
   */
  @CryptField
  private String userName;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * user.age
   *
   * @mbg.generated Sat Jun 12 13:37:40 CST 2021
   */
  private Integer age;

}
